# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    banner: false

# Logger Config
logging:
  level:
    mybatis.mate: debug
